#!/bin/bash -e
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)

BROWSER_DIR=$SCRIPT_DIR/kmp/build/js/packages/pskov-ver-browser/kotlin
DIST_DIR=$SCRIPT_DIR/dist
PROJECT_DIR=$1
SERVER_DIR=$SCRIPT_DIR/kmp/build/js/packages/pskov-ver-nodejs/kotlin

# Enter KMP dir to run Gradle
wasDir=$(pwd)
cd $SCRIPT_DIR/kmp 

# Special case to rerun yarn only
if [ "$PROJECT_DIR" == "reyarn" ]; then
    ./gradlew kotlinUpgradeYarnLock
    exit
fi

# Build client
./gradlew jsBrowserDistribution
# Build server
./gradlew jsNodeDevelopmentRun

# Exit KMP dir
cd $wasDir

# Make distribution
rm -fR $DIST_DIR/*
mkdir -p $DIST_DIR/{ver-browser,ver-nodejs}
cp $SCRIPT_DIR/util/package.json $DIST_DIR
cp -R $BROWSER_DIR/* $DIST_DIR/ver-browser
cp -R $SERVER_DIR/* $DIST_DIR/ver-nodejs
rm $DIST_DIR/ver-nodejs/*dom_api*
rm $DIST_DIR/*/*map

if [ -z "$PROJECT_DIR" ]; then
    echo "Usage: $0 PROJECT_DIR"
    exit 1
fi

# Run server
cd $DIST_DIR
npm install
npm run start -- --browserDir=ver-browser --projectDir=../$PROJECT_DIR
