#!/bin/bash -e
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)

PROJECT_DIR=$1

if [ -z "$PROJECT_DIR" ]; then
    echo "Usage: $0 PROJECT_DIR"
    exit 1
fi

cd $SCRIPT_DIR/kmp

# Special case to rerun yarn only
if [ "$PROJECT_DIR" == "reyarn" ]; then
    ./gradlew kotlinUpgradeYarnLock
    exit
fi

# Build client
./gradlew jsBrowserDistribution
# Build server
./gradlew jsNodeDevelopmentRun

# Run server
BROWSER_DIR=$SCRIPT_DIR/kmp/build/js/packages/pskov-ver-browser/kotlin
SERVER_DIR=$SCRIPT_DIR/kmp/build/js/packages/pskov-ver-nodejs/kotlin
node $SERVER_DIR/srv.js --browserDir=$BROWSER_DIR --projectDir=$PROJECT_DIR
