#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)

REYARN=$1

cd $SCRIPT_DIR/kmp

if [ "$REYARN" == "1" ]; then
    ./gradlew kotlinUpgradeYarnLock
fi
./gradlew jsNodeDevelopmentRun

node $SCRIPT_DIR/kmp/build/js/packages/pskov-ver-nodejs/kotlin/srv.js
