#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)
T=$SDIR/step
source $SDIR/other

AND_DIR=$SDIR/../ver-android/app/src/main/kotlin/org/opengamestudio
CLD_DIR=$SDIR/../../cross-language-dialect
NODE_DIR=$SDIR/../kmp/ver-nodejs/src/commonMain/kotlin/org/opengamestudio
SRC_DIR=$SDIR/../src

STEP=0

####
echo -e "\nSynchronize CLD files..."
####

FILES=(
  CLDContext.kt
  CLDController.kt
  registerOneliners.kt
)

for file in ${FILES[@]}; do
    echo "> $file"

    # Copy original CLD files for browser and Node.js
    cp $CLD_DIR/kotlin/$file $SRC_DIR
    cd $SRC_DIR
    # Add JS export
    replace $file "package org.opengamestudio" "package org.opengamestudio\nimport kotlin.js.JsExport"
    replace $file "interface CLD" "@JsExport\ninterface CLD"
    replace $file "class CLD" "@JsExport\nclass CLD"
    replace $file "fun registerOne" "@JsExport\nfun registerOne"
done

source $T/copyCLDForAndroid
source $T/copySrcForAndroid
