#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

CLD_DIR=$SDIR/../../cross-language-dialect
SRC_DIR=$SDIR/../src

function replace {
    file=$1
    was=$2
    now=$3
    cmd="sed -i '' 's/$was/$now/g' $file"
    eval "$cmd"
}

####
echo -e "\nSynchronize CLD files..."
####

FILES=(
  CLDContext.kt
  CLDController.kt
  registerOneliners.kt
)

for file in ${FILES[@]}; do
    echo "> $file"
    # Копируем оригинал из CLD
    cp $CLD_DIR/kotlin/$file $SRC_DIR
    cd $SRC_DIR
    # Исправляем пакет и импорты
#    replace $file "package org.opengamestudio" "package su.kot\nimport kotlin.js.JsExport"
#    # Делаем сущности доступными в JS
#    replace $file "interface CLD" "@JsExport\ninterface CLD"
#    replace $file "class CLD" "@JsExport\nclass CLD"
#    replace $file "fun registerOne" "@JsExport\nfun registerOne"
done
