#!/bin/bash -e

# Absolute path to this script
SCRIPT_DIR=$(cd "$(dirname "$0")" ; pwd -P)

DST_COMMON=$SCRIPT_DIR/../src/entities.kt

# Path to Cross-language dialect's translator
TR=$SCRIPT_DIR/../../cross-language-dialect/translator
$TR/run/run-java --file=$SCRIPT_DIR/entities.yml --out=$DST_COMMON
